// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektSklepTI.DAL;

#nullable disable

namespace ProjektSklepTI.Migrations
{
    [DbContext(typeof(FilmsContext))]
    [Migration("20250428140729_test23")]
    partial class test23
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjektSklepTI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Desc = "Movies full of dynamic scenes, chases, and intense action.",
                            Name = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            Desc = "Movies focused on humor and light-hearted entertainment.",
                            Name = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            Desc = "Movies that focus on emotional depth and character conflict.",
                            Name = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            Desc = "Movies designed to evoke fear and suspense.",
                            Name = "Horror"
                        },
                        new
                        {
                            CategoryId = 5,
                            Desc = "Movies that explore futuristic and technological themes.",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 6,
                            Desc = "Movies centered around love stories and relationships.",
                            Name = "Romance"
                        },
                        new
                        {
                            CategoryId = 7,
                            Desc = "Movies filled with suspense, tension, and unexpected twists.",
                            Name = "Thriller"
                        },
                        new
                        {
                            CategoryId = 8,
                            Desc = "Movies set in magical or fantastical worlds.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 9,
                            Desc = "Movies documenting real-life events, people, or topics.",
                            Name = "Documentary"
                        },
                        new
                        {
                            CategoryId = 10,
                            Desc = "Movies created using animation techniques, for both kids and adults.",
                            Name = "Animation"
                        });
                });

            modelBuilder.Entity("ProjektSklepTI.Models.Film", b =>
                {
                    b.Property<int>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = 1,
                            CategoryId = 1,
                            Desc = "In a post-apocalyptic wasteland, Max teams up with a warrior to escape a tyrannical warlord.",
                            Director = "George Miller",
                            Poster = "1.jpg",
                            Price = 12.99m,
                            Title = "Mad Max: Fury Road"
                        },
                        new
                        {
                            FilmId = 2,
                            CategoryId = 1,
                            Desc = "A retired hitman seeks revenge against the people who killed his dog.",
                            Director = "Chad Stahelski",
                            Poster = "2.jpg",
                            Price = 14.99m,
                            Title = "John Wick"
                        },
                        new
                        {
                            FilmId = 3,
                            CategoryId = 1,
                            Desc = "A New York cop faces off against terrorists in a Los Angeles skyscraper.",
                            Director = "John McTiernan",
                            Poster = "3.jpg",
                            Price = 9.99m,
                            Title = "Die Hard"
                        },
                        new
                        {
                            FilmId = 4,
                            CategoryId = 1,
                            Desc = "Batman faces off against the Joker, a criminal mastermind bent on chaos.",
                            Director = "Christopher Nolan",
                            Poster = "4.jpg",
                            Price = 13.99m,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            FilmId = 5,
                            CategoryId = 1,
                            Desc = "A betrayed Roman general seeks revenge against the corrupt emperor who murdered his family.",
                            Director = "Ridley Scott",
                            Poster = "5.jpg",
                            Price = 11.99m,
                            Title = "Gladiator"
                        },
                        new
                        {
                            FilmId = 6,
                            CategoryId = 2,
                            Desc = "Two high school seniors try to make the most of their last days before graduation.",
                            Director = "Greg Mottola",
                            Poster = "6.jpg",
                            Price = 8.99m,
                            Title = "Superbad"
                        },
                        new
                        {
                            FilmId = 7,
                            CategoryId = 2,
                            Desc = "Three friends wake up from a bachelor party with no memory of the previous night and must piece together the events.",
                            Director = "Todd Phillips",
                            Poster = "6.jpg",
                            Price = 10.99m,
                            Title = "The Hangover"
                        },
                        new
                        {
                            FilmId = 8,
                            CategoryId = 2,
                            Desc = "Two dim-witted friends embark on a cross-country trip to return a suitcase full of money.",
                            Director = "Peter Farrelly",
                            Poster = "8.jpg",
                            Price = 7.99m,
                            Title = "Dumb and Dumber"
                        },
                        new
                        {
                            FilmId = 9,
                            CategoryId = 2,
                            Desc = "Two undercover cops are sent to a high school to bust a drug ring.",
                            Director = "Phil Lord",
                            Poster = "9.jpg",
                            Price = 9.49m,
                            Title = "21 Jump Street"
                        },
                        new
                        {
                            FilmId = 10,
                            CategoryId = 2,
                            Desc = "The chaos that follows when a new female anchor joins a 1970s news team.",
                            Director = "Adam McKay",
                            Poster = "10.jpg",
                            Price = 8.49m,
                            Title = "Anchorman"
                        },
                        new
                        {
                            FilmId = 11,
                            CategoryId = 3,
                            Desc = "Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.",
                            Director = "Frank Darabont",
                            Poster = "11.jpg",
                            Price = 12.49m,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            FilmId = 12,
                            CategoryId = 3,
                            Desc = "The presidencies of Kennedy and Johnson, the Vietnam War, the civil rights movement, and other historical events unfold from the perspective of an Alabama man with an extraordinary life.",
                            Director = "Robert Zemeckis",
                            Poster = "12.jpg",
                            Price = 11.99m,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            FilmId = 13,
                            CategoryId = 3,
                            Desc = "The story of mathematician John Nash, who struggles with schizophrenia and tries to make a name for himself while dealing with the disorder.",
                            Director = "Ron Howard",
                            Poster = "13.jpg",
                            Price = 9.99m,
                            Title = "A Beautiful Mind"
                        },
                        new
                        {
                            FilmId = 14,
                            CategoryId = 3,
                            Desc = "A struggling salesman takes custody of his son as he's poised to begin a life-changing professional career.",
                            Director = "Gabriele Muccino",
                            Poster = "14.jpg",
                            Price = 10.49m,
                            Title = "The Pursuit of Happyness"
                        },
                        new
                        {
                            FilmId = 15,
                            CategoryId = 3,
                            Desc = "An insomniac office worker forms an underground fight club with a soap salesman, leading to unintended consequences.",
                            Director = "David Fincher",
                            Poster = "15.jpg",
                            Price = 9.79m,
                            Title = "Fight Club"
                        },
                        new
                        {
                            FilmId = 16,
                            CategoryId = 4,
                            Desc = "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
                            Director = "James Wan",
                            Poster = "16.jpg",
                            Price = 10.99m,
                            Title = "The Conjuring"
                        },
                        new
                        {
                            FilmId = 17,
                            CategoryId = 4,
                            Desc = "Several people are hunted by a man who uses their fear of the dark and sleep to murder them in their dreams.",
                            Director = "Wes Craven",
                            Poster = "17.jpg",
                            Price = 9.49m,
                            Title = "A Nightmare on Elm Street"
                        },
                        new
                        {
                            FilmId = 18,
                            CategoryId = 4,
                            Desc = "When a young girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her.",
                            Director = "William Friedkin",
                            Poster = "18.jpg",
                            Price = 11.99m,
                            Title = "The Exorcist"
                        },
                        new
                        {
                            FilmId = 19,
                            CategoryId = 4,
                            Desc = "A group of misfit children band together to defeat a shape-shifting entity that terrorizes their town.",
                            Director = "Andy Muschietti",
                            Poster = "19.jpg",
                            Price = 12.99m,
                            Title = "It"
                        },
                        new
                        {
                            FilmId = 20,
                            CategoryId = 4,
                            Desc = "A grieving family is haunted after the death of their secretive grandmother.",
                            Director = "Ari Aster",
                            Poster = "20.jpg",
                            Price = 13.49m,
                            Title = "Hereditary"
                        },
                        new
                        {
                            FilmId = 21,
                            CategoryId = 5,
                            Desc = "A thief who enters the dreams of others to steal secrets from their subconscious is given the task of planting an idea into a target's subconscious.",
                            Director = "Christopher Nolan",
                            Poster = "21.jpg",
                            Price = 14.99m,
                            Title = "Inception"
                        },
                        new
                        {
                            FilmId = 22,
                            CategoryId = 5,
                            Desc = "A blade runner must pursue and terminate four replicants who stole a ship in space, and have returned to Earth to find their creator.",
                            Director = "Ridley Scott",
                            Poster = "22.jpg",
                            Price = 12.99m,
                            Title = "Blade Runner"
                        },
                        new
                        {
                            FilmId = 23,
                            CategoryId = 5,
                            Desc = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Poster = "23.jpg",
                            Price = 13.49m,
                            Title = "The Matrix"
                        },
                        new
                        {
                            FilmId = 24,
                            CategoryId = 5,
                            Desc = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Director = "Christopher Nolan",
                            Poster = "24.jpg",
                            Price = 15.99m,
                            Title = "Interstellar"
                        },
                        new
                        {
                            FilmId = 25,
                            CategoryId = 5,
                            Desc = "A young farmer sets out to rescue a princess from an evil galactic empire with the help of a powerful force and a team of companions.",
                            Director = "George Lucas",
                            Poster = "25.jpg",
                            Price = 14.49m,
                            Title = "Star Wars: A New Hope"
                        });
                });

            modelBuilder.Entity("ProjektSklepTI.Models.Film", b =>
                {
                    b.HasOne("ProjektSklepTI.Models.Category", "Category")
                        .WithMany("Films")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProjektSklepTI.Models.Category", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
